import numpy as np
import copy

class Body:
    def __init__(self, mass, pos, vel, soi_radius, radius=0.5, color='grey', orbit_color='r--'):
        self.mass = mass
        self.pos = np.array(pos, dtype=float)
        self.vel = np.array(vel, dtype=float)
        self.soi_radius = float(soi_radius)
        self.radius = radius
        self.color = color
        self.orbit_color = orbit_color

class SolarSystem:
    @staticmethod
    def create():
        return {
            "mercury": Body(
                mass=0.5, pos=[150.0, 177.0], vel=[0.304, 0.0],
                soi_radius=1.5, radius=0.3, color='#8c8c8c', orbit_color='r--'
            ),
            "venus": Body(
                mass=8.0, pos=[150.0, 200.0], vel=[0.223, 0.0],
                soi_radius=4.5, radius=0.7, color='#e3bb76', orbit_color='r--'
            ),
            "earth": Body(
                mass=10.0, pos=[150.0, 220.0], vel=[0.195, 0.0],
                soi_radius=6.5, radius=0.75, color='#3b8ad4', orbit_color='r--'
            ),
            "moon": Body(
                mass=1.0, pos=[150.0, 224.5], vel=[0.345, 0.0],
                soi_radius=0.8, radius=0.2, color='#c9d1d9', orbit_color='r--'
            ),
            "mars": Body(
                mass=4.0, pos=[150.0, 25.0], vel=[-0.144, 0.0],
                soi_radius=4.0, radius=0.5, color='#ff4444', orbit_color='r--'
            ),
            "jupiter": Body(
                mass=50.0, pos=[150.0, 510.0], vel=[0.083, 0.0],
                soi_radius=25.0, radius=2.5, color='#c99867', orbit_color='r--'
            ),
            "saturn": Body(
                mass=30.0, pos=[150.0, -500.0], vel=[-0.062, 0.0],
                soi_radius=20.0, radius=2.0, color='#e3d599', orbit_color='r--'
            ),
        }

class SpaceEngine:
    def __init__(self):
        self.sun_mass = 250
        self.sun_pos = np.array([150.0, 150.0])
        self.GRAV_CONSTANT = 0.01
        
        self.bodies = SolarSystem.create()


    def calculate_gravity(self, pos1, pos2, mass):
        displacement = pos1 - pos2
        r = np.linalg.norm(displacement)
        if r < 1e-6:
            return np.zeros(2)
        return self.GRAV_CONSTANT * (mass / (r**2)) * (displacement / r)

    def calculate_orbit(self, pos1, pos2, mass, vec):
        displacement = pos1 - pos2
        mod_r = np.linalg.norm(displacement)
        mod_v_squared = np.square(np.linalg.norm(vec))
        mew = self.GRAV_CONSTANT * mass
        
        a = 1 / (2 / mod_r - mod_v_squared / mew)
        e_vec = ((mod_v_squared - mew / mod_r) * displacement - np.dot(displacement, vec) * vec) / mew
        e = np.linalg.norm(e_vec) 
        omega = float(np.arctan2(e_vec[1], e_vec[0])) if e > 0.0005 else 0.0
        
        theta = np.linspace(0, 2 * np.pi, 80)
        r_orbit = (a * (1 - e**2)) / (1 + e * np.cos(theta))
        r_orbit[np.abs(r_orbit) > 1000] = np.nan
        
        x_local = r_orbit * np.cos(theta)
        y_local = r_orbit * np.sin(theta)
        x_world = pos2[0] + (x_local * np.cos(omega) - y_local * np.sin(omega))
        y_world = pos2[1] + (x_local * np.sin(omega) + y_local * np.cos(omega))
        return x_world, y_world

    def get_influence(self, current_name, current_pos):
        for name, data in self.bodies.items():
            if name != current_name:
                if np.linalg.norm(current_pos - data.pos) < data.soi_radius:
                    return name
        return "sun"

    def step(self, dt):
        new_states = {}
        for name, data in self.bodies.items():
            current_pos = data.pos.copy()
            current_vel = data.vel.copy()
            parent = self.get_influence(name, current_pos)

            if parent == "sun":
                current_vel += self.calculate_gravity(self.sun_pos, current_pos, self.sun_mass) * dt
            else:
                parent_data = self.bodies[parent]
                current_vel += self.calculate_gravity(self.sun_pos, parent_data.pos, self.sun_mass) * dt
                current_vel += self.calculate_gravity(parent_data.pos, current_pos, parent_data.mass) * dt

            current_pos += current_vel * dt
            new_states[name] = (current_pos, current_vel)

        for name, (pos, vel) in new_states.items():
            self.bodies[name].pos = pos
            self.bodies[name].vel = vel

    #### FUNCTION GENERATED BY AI: run_simulation
    def run_simulation(self, total_frames=60, dt=0.7, step_size=0.1):
        history = []
        sub_steps = max(1, int(np.round(dt / step_size))) if dt > 0 else 0
        small_dt = dt / sub_steps if sub_steps > 0 else 0

        for _ in range(total_frames):
            for _ in range(sub_steps):
                self.step(small_dt)

            frame_data = {
                "sun": {"pos": self.sun_pos.tolist(), "radius": 4, "color": "orange"},
                "bodies": {}
            }

            for name, data in self.bodies.items():
                parent = self.get_influence(name, data.pos)
                if parent == "sun":
                    x_pts, y_pts = self.calculate_orbit(data.pos, self.sun_pos, self.sun_mass, data.vel)
                else:
                    parent_data = self.bodies[parent]
                    x_local, y_local = self.calculate_orbit(
                        data.pos - parent_data.pos, np.array([0.0, 0.0]), parent_data.mass, data.vel - parent_data.vel
                    )
                    x_pts = x_local + parent_data.pos[0]
                    y_pts = y_local + parent_data.pos[1]

                orbit_points = []
                for x, y in zip(x_pts, y_pts):
                    if not (np.isnan(x) or np.isnan(y)):
                        orbit_points.append({"x": float(x), "y": float(y)})

                frame_data["bodies"][name] = {
                    "pos": data.pos.tolist(),
                    "radius": float(data.radius),
                    "soi_radius": float(data.soi_radius),
                    "color": data.color,
                    "orbit": orbit_points
                }
            history.append(frame_data)
        return history